### ISSUE TITLE
Assert is not supported in this version

### ISSUE THREAD

**Issue by guwenjin** [Schemarise/demo-alfa-project#1]
alfa-java-samples project compilation failed. the message is :
[..\..\..\..\..\..\..\model\common.alfa:17] Assert is not supported in this version
Expression is not supported in this version
[..\..\..\..\..\..\..\model\common.alfa:24] library is not supported in this version
Expression is not supported in this version

**Comment by alfa-demo** [comment]
The demo uses features not available in the free version (assert and library), but the demo includes an evaluation license in the .alfa directory.

If you set an environment variable named ALFA_HOME with the path to the .alfa directory, the ALFA compiler will find the alfa-license.ini file there. ( e.g. export ALFA_HOME=/apps/alfa-sample-project/.alfa/)

**Comment by alfa-demo** [comment]
Hope that clarified, Let us know if not.
